<html>
    <title>
            packages
    </title>
        <head>
            <style>
p {
  text-shadow: 2px 2px 8px #FF0000;
  text-align:center;
}
                .a{
                    text-decoration:none;
                    color:black;
                    font-family: Arial, Helvetica, sans-serif;
                }
                
                .ul{
                    font-size:12px;
                    margin-left:170px;
                    margin-top:-20px;
                    color:green;
                    font-family: Courier;

                }
                
                .abt{
                    height:300px;
                    width:1100px;
                    background-color:ghostwhite;
                    position:absolute;
                    margin-top:1920px; 
                    font-size: 16px;
                    font-family: monospace;
                    margin-left: 0px;
                    text-align: center;
                
                    }
                .h4{
                    margin-left:10px;
                    color:red;
                }
                .main{
                    height:3300px;
                    width:1570px;
                    background-color:ghostwhite;
                }
                .ab{
                    height:270px;
                    width:1100px;
                    background-color:yellow;
                    position:absolute;
                }

</style>
        </head>
    <body>
        <div class="main">
            <div style="height:353px;background-color:yellow">
                <div style="background-image: url(img/fp/caravan.jpg);height:353px;background-repeat:none;background-size:cover">
                        <div style="height: 150px;width: 200px;margin-left: 100px">
                             <img src="img/imgs/Royal-Dalmatia.png" height="150px" width="300px">
                        </div>
                </div>
                <div style="height:104px;background-color:green">
                    <img src="img/fp/ss.png" height="104px" width="1570px">
                </div>
                <div style="height:1900px;width:1100px;background-color:ghostewhite;margin-left:240px;margin-top:30px">
                    <div class="ab">
                        <div>
                            <img src="img\imgs\jaipur\jantarmantar.jpg" height="270px" width="300px">
                        </div>
                        <div style="height:270px;width:800px;background-color:white;margin-left:300px;margin-top:-270px;position:absolute">
                            
                            <h1 style="margin-left:300px"><a href="Jaipur.php" class="a">JAIPUR</a></h1>
                            
                            <p >
                                Jaipur is the capital of India’s Rajasthan state.<br/> It evokes the royal family that once ruled the region and that,<br/> in 1727, founded what is now called the Old City, or <b>“Pink City”</b> for its trademark building color.
                            </p>
                            <h4 class="h4"><b>POINTS OF INTREST:</b>
                                
                            </h4>
                            <ul class="ul">
                                <li>AMBER PALACE</li>  
                                <li>CITY PALACE</li>
                                <li>HAWA MAHAL</li>
                                <li>JANTAR MANTAR</li>
                                <li>JAL MAHAL</li>
                            </ul>

                        </div>
                        <div style="height:270px;width:1100px;background-color:blue;margin-top:40px;position:absolute">
                        <div style="height:270px;width:300px;background-color:green">
                            <img src="img/imgs/udaipur/india-1656547.jpg" height="270px" width="300px">
                        </div>
                            <div style="height:270px;width:800px;background-color:white;margin-left:300px;margin-top:-270px;position:absolute">
                                <h1 style="margin-left:300px"><a href="udaipur.php" class="a">UDAIPUR</a></h1>
                                
                                <p>
                                        Formerly the capital of the Mewar Kingdom, is a city in the western Indian state of Rajasthan. <br/>Founded by Maharana Udai Singh II in 1559, <br/>it’s set around a series of artificial lakes and is known for its lavish royal residences.
                                </p>
                                <h4 class="h4"><b>POINTS OF INTREST:</b></h4>
                                <ul class="ul">
                                                <li>CITY PALACE</li>
                                                <li>LAKE PICHOLA</li>
                                                <li>JAGMANDIR</li>
                                                <li>SAHELIYON KI BADI</li>
                                                <li>FATEH SAGAR</li>
  
  
                                </ul>
                            </div>
                        </div>
                        <div style="height:270px;width:1100px;background-color:blue;margin-top:350px;position:absolute">
                        <div style="height:270px;width:300px;background-color:green">
                            <img src="img/imgs/jodhpur/india-2895905.jpg" height="270px" width="300px">
                        </div>
                            <div style="height:270px;width:800px;background-color:white;margin-left:300px;margin-top:-270px;position:absolute">
                                <h1 style="margin-left:300px"><a href="#" class="a">JODHPUR</a></h1>
                                
                                <p>
                                    DescriptionJodhpur is a city in the Thar Desert of the northwest Indian state of Rajasthan. <BR/>Its 15th-century Mehrangarh Fort is a former palace </br>that’s now a museum, displaying weapons, paintings and elaborate royal palanquins (sedan chairs). 
                                <h4 class="h4"><b>POINTS OF INTREST:</b></h4>
                                <ul class="ul">
                                                <li>MEHRANGARH FORT</li>
                                                <li>UMMAID BHAWAN PALACE</li>
                                                <li>JASWANT THADA</li>
                                                <li>KAYLANA LAKE</li>
                                                <li>BALSAMAND LAKE</li>
  
  
                                </ul>
                            </div>
                        </div>
                    
                    <div style="height:270px;width:1100px;background-color:blue;margin-top:670px;position:absolute">
                        <div style="height:270px;width:300px;background-color:green">
                            <img src="img\imgs\mount abu\dilwara-temple-rajasthan.jpg" height="270px" width="300px">
                        </div>
                            <div style="height:270px;width:800px;background-color:white;margin-left:300px;margin-top:-270px;position:absolute">
                                <h1 style="margin-left:300px"><a href="#" class="a">MOUNT ABU</a></h1>
                                
                                <p>
                                    Mount Abu is a hill station in western India’s Rajasthan state, near the Gujarat border.<BR/> Set on a high rocky plateau in the Aravalli Range and surrounded by forest, <BR/>it offers a relatively cool climate and views over the arid plains below
                                <h4 class="h4"><b>POINTS OF INTREST:</b></h4>
                                <ul class="ul">
                                                <li>GOA GAON</li>
                                                <li>DELWARA MANDIR</li>
                                                <li>HILLS</li>
                                                <li>AMBEDKAR COLONY</li>
                                                <li>ABU ROAD</li>
  
  
                                </ul>
                            </div>
                        </div>
                    
                        <div style="height:270px;width:1100px;background-color:blue;margin-top:1000px;position:absolute">
                        <div style="height:270px;width:300px;background-color:green">
                            <img src="img\imgs\chittorgarh\chittorgarh-2964778.jpg" height="270px" width="300px">
                        </div>
                            <div style="height:270px;width:800px;background-color:white;margin-left:300px;margin-top:-270px;position:absolute">
                                <h1 style="margin-left:300px"><a href="#" class="a">CHITTORGARH</a></h1>
                                
                                <p>
                                    Chittorgarh is a city and municipality in Rajasthan, northwest India.<br/>   It’s known for the honey-colored, 7th-century Chittorgarh Fort, a vast hilltop complex<br/> with the remains of many temples and monuments.<br/> The 15th-century, 9-story Vijay Stambh (Tower of Victory) is built from red sandstone and white marble.
                                <h4 class="h4"><b>POINTS OF INTREST:</b></h4>
                                <ul class="ul">
                                                <li>CHITTORGARH FORT</li>
                                                <li>VIJAY STAMBH</li>
                                                <li>MEERA TEMPLE</li>
                                                <li>KALIKA MATA TEMOLE</li>
                                                
  
  
                                </ul>
                            </div>
                        </div>
                    
                        <div style="height:270px;width:1100px;background-color:blue;margin-top:1330px;position:absolute">
                        <div style="height:270px;width:300px;background-color:green">
                            <img src="img\imgs\jaislmer\jsl.jpg" height="270px" width="300px">
                        </div>
                            <div style="height:270px;width:800px;background-color:white;margin-left:300px;margin-top:-270px;position:absolute">
                                <h1 style="margin-left:300px"><a href="#" class="a">JAISALMER</a></h1>
                                
                                <p>
                                   DescriptionJaisalmer is a former medieval trading center and a princely state in the western Indian state of Rajasthan, <BR/>in the heart of the Thar Desert. Known as the "Golden City," <br/>it's distinguished by its yellow sandstone architecture. 
                                <h4 class="h4"><b>POINTS OF INTREST:</b></h4>
                                <ul class="ul">
                                                <li>JAISLMER FORT FORT</li>
                                                <li>PATWO KI HAWELI</li>
                                                <li>GADISAR LAKE</li>
                                                <li>NATHMAL KI HAWELI</li>
                                                
  
  
                                </ul>
                            </div>
                        </div>

                     

                     
                </div>
                <div class="abt">
                    Rajasthan literally, "Land of Kings")[7] is a state in northern India.[8][9][10] The state covers an area of 342,239 square kilometres (132,139 sq mi) or 10.4 percent of the total geographical area of India. It is the largest Indian state by area and the seventh largest by population. Rajasthan is located on the northwestern side of India, where it comprises most of the wide and inhospitable Thar Desert (also known as the "Rajasthan Desert" and "Great Indian Desert") and shares a border with the Pakistani provinces of Punjab to the northwest and Sindh to the west, along the Sutlej-Indus river valley. Elsewhere it is bordered by five other Indian states: Punjab to the north; Haryana and Uttar Pradesh to the northeast; Madhya Pradesh to the southeast; and Gujarat to the southwest.

Major features include the ruins of the Indus Valley Civilisation at Kalibanga and Balathal; the Dilwara Temples, a Jain pilgrimage site at Rajasthan's only hill station, Mount Abu, in the ancient Aravalli mountain range; and, in eastern Rajasthan, the Keoladeo National Park near Bharatpur, a World Heritage Site[11] known for its bird life. Rajasthan is also home to three national tiger reserves, the Ranthambore National Park in Sawai Madhopur, Sariska Tiger Reserve in Alwar and Mukundra Hill Tiger Reserve in Kota.


                </div>
                <div style="height:248px;width:1569;background-color:blue;position:absolute;margin-top:2565px;margin-left:-240px" >
                    <img src="img/fp/end.png">
                </div>
            </div>
        </div>
    </body>
</html>